### ISSUE TITLE
Build fails for pypy and python 3.2

### ISSUE THREAD

**Issue by balavignesh-s** [shippableSamples/sample_python_postgres#2]
The following error occurs during pip install requirements.txt

In file included from psycopg/psycopgmodule.c:38:0:

./psycopg/error.h:32:5: error: unknown type name ‘PyBaseExceptionObject’

error: command 'cc' failed with exit status 1

----------------------------------------
Cleaning up...
Command /home/shippable/build_ve/python/pypy/bin/pypy -c "import setuptools, tokenize;__file__='/home/shippable/build_ve/python/pypy/build/psycopg2/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-jhFgW0-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/shippable/build_ve/python/pypy/include/site/python2.7 failed with error code 1 in /home/shippable/build_ve/python/pypy/build/psycopg2
Traceback (most recent call last):
  File "app_main.py", line 72, in run_toplevel
  File "/home/shippable/build_ve/python/pypy/bin/pip", line 11, in 
    sys.exit(main())
  File "/home/shippable/build_ve/python/pypy/site-packages/pip/__init__.py", line 185, in main
    return command.main(cmd_args)
  File "/home/shippable/build_ve/python/pypy/site-packages/pip/basecommand.py", line 161, in main
    text = '\n'.join(complete_log)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 53: ordinal not in range(128)

**Comment by balavignesh-s** [comment]
Looks like coverage doesnot support 3.2 and pypy. Look at this link https://pypi.python.org/pypi/coverage/4.0.3.
